set-option global tabstop 2
set-option global indentwidth 0

# Yes, this weird slash is really necessary, don't touch it
add-highlighter global/ number-lines -relative
colorscheme dracula

# Config stuff
map global normal <c-k> ":edit ~/.config/kak/kakrc <ret>"
map global normal <c-p> ":edit ~/.config/kak-lsp/kak-lsp.toml <ret>"

map global normal <c-l> :bn<ret>
# map global normal <c-h> :bp<ret>
map global normal <c-w> :db<ret>


# In case we're using LSPs
# eval %sh{kak-lsp --kakoune -s $kak_session}

# If shit goes bad
# eval %sh{ (kak-lsp -vvv) > /tmp/kak-lsp.log 2>&1 < /dev/null & }

# set-option global lsp_insert_spaces true


## Plugins
source "%val{config}/plugins/plug.kak/rc/plug.kak"

# plug "tgirod/tidal.kak"
plug "https://github.com/alexherbo2/explore.kak"
plug "https://github.com/tgirod/tidal.kak"
# plug "https://github.com/andreyorst/fzf.kak"
# plug "https://github.com/alexherbo2/connect.kak"

# require-module connect

# Enable directory exploring
require-module explore


# Clipboard
plug "lePerdu/kakboard" %{
  hook global WinCreate .* %{ kakboard-enable }
}



plug "andreyorst/kaktree" config %{
    hook global WinSetOption filetype=kaktree %{
        remove-highlighter buffer/numbers
        remove-highlighter buffer/matching
        remove-highlighter buffer/wrap
        remove-highlighter buffer/show-whitespaces
    }
    kaktree-enable
}



# Load Boot.tidal
set-option global tidal_boot_file "/home/tidal/boot.tidal"

# Set tidal syntax to haskell
declare-option bool no_tidal_repl_yet true

hook global BufCreate .+\.tidal -once %{
  alias global repl tmux-repl-window
  tidal-start-repl
  tmux-focus
}

# hook global BufCreate .+\.tidal %{
  # set buffer filetype haskell
# }

map global normal <c-e> ':tidal-send-block<ret>'
map global normal <c-h> ':tidal-hush<ret>'

# :tidal-start-repl
# :tidal-start-superdirt
# :tidal-send-line
# :tidal-send-block
# :tidal-hush